---
deployment:
  tasks:
    - source ~/.bashrc
    - cd /home/$USERNAME/public_html/lms
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate
    - php artisan optimize:clear