---
deployment:
  tasks:
    - source ~/.bashrc
    - cd /home/$USERNAME/public_html/lms
    - composer install --no-dev --optimize-autoloader
    # - php artisan migrate
    # Comment this line if web application was production version
    - php artisan migrate:refresh
    - php artisan db:seed
    # -----------------------------------------------------------
    - php artisan optimize:clear